In [1]:
import numpy as np

In [2]:
np.array([1,2,3,45.54])

array([ 1.  ,  2.  ,  3.  , 45.54])

In [3]:
np.array(['raj', 3,4.5, 3+4j])

array(['raj', '3', '4.5', '(3+4j)'], dtype='<U64')

In [4]:
a = np.array([5,6,7])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([4, 5,6.7], dtype = complex)

array([4. +0.j, 5. +0.j, 6.7+0.j])

In [7]:
np.array([5,6,7,8], dtype = str)

array(['5', '6', '7', '8'], dtype='<U1')

In [8]:
b = np.asarray([3,4,5,6])

In [9]:
b

array([3, 4, 5, 6])

In [10]:
type(b)

numpy.ndarray

In [11]:
# np.asarray and np.array gives the numpy.ndarray

In [12]:
np.asarray([4,5,7,8], dtype = np.float16)

array([4., 5., 7., 8.], dtype=float16)

In [13]:
mat = np.matrix([5,6])

In [14]:
mat

matrix([[5, 6]])

In [15]:
type(mat) #matrix is a subclass of array

numpy.matrix

In [16]:
# minimum 2d data we will receive from np.matrix

In [17]:
# if something is available in any of the array format it will not do a conversion
#matrix is a subclass of array, so it won't convert the matrix into array
np.asanyarray(mat)

matrix([[5, 6]])

In [18]:
#but for any list
l = [2,3,4,5,6]
l

[2, 3, 4, 5, 6]

In [19]:
type(l)

list

In [20]:
l1 = np.asanyarray(l)

In [21]:
type(l1) #converted list to array

numpy.ndarray

In [22]:
# np.fromfuncrtion - whatever operation we are going to do inside this from function
# it will return me an araryy


np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
np.fromfunction(lambda i,j : i**j, (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [25]:
np.fromfunction(lambda i,j : i**i, (3,3), dtype = int)
# it is not going to work if the data type str 

array([[1, 1, 1],
       [1, 1, 1],
       [4, 4, 4]], dtype=int32)

In [26]:
# np.fromstring = try to make an array with tha data that available into string format
# the availabe string in data should be numerical and charactors
np.fromstring("raj sahu", sep = " ")

C:\Users\himan\AppData\Local\Temp\ipykernel_13532\1564731327.py:3: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("raj sahu", sep = " ")


array([], dtype=float64)

In [27]:
np.fromstring("23 56", sep = " ", dtype = int)

array([23, 56])

In [28]:
np.fromstring("23 56", sep = "5", dtype = int)

array([23,  6])

In [29]:
np.fromstring("4,6", sep = ",")

array([4., 6.])

In [30]:
a1 = np.array([5,6,7,8,9])
a2 = np.array([[3,4,5,6,7]])
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(a1)
print(a1.ndim)

[5 6 7 8 9]
1


In [ ]:
print(a2)
print(a2.ndim)

In [33]:
print(a3)
print(a3.ndim)

In [34]:
# array.size function gives the size that is number of elements
print(a1.size)
print(a2.size)
print(a3.size)

5
5
9


In [35]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(5,)
(1, 5)
(3, 3)


In [36]:
np.array([(2,3,4,5,6), (3,4,5,5,6)])
# here the data has been passed as a list of tuples
# np.array will directly convert it into array
# but for that both the tuples should have same numbers of data

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 5, 6]])

In [37]:
np.array([(2,3,4,5,6), (3,4,5,5,6,8)])

C:\Users\himan\AppData\Local\Temp\ipykernel_13532\703324218.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([(2,3,4,5,6), (3,4,5,5,6,8)])


array([(2, 3, 4, 5, 6), (3, 4, 5, 5, 6, 8)], dtype=object)

In [38]:
# np.arange function
# first simple range function
range(10)

range(0, 10)

In [39]:
print(list(range(10)))
print(list(range(5,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9]


In [40]:
# but as we try to enter any floating point value this will give an error
# that's why we needed np.arange function to deal with floats
np.arange(5,10.5)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [41]:
np.arange(5,10.5,.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [42]:
list(np.arange(5,10.5,.5))

[5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0]

In [43]:
tuple(np.arange(5,10.5,.5))

(5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0)

In [44]:
np.fromstring("43982734", sep = "2")

array([43982734.])

In [45]:
np.fromstring("23 56" , sep = "5")

array([23.,  6.])

In [46]:
# Return evenly spaced numbers over a specified interval. and total gives 50 data
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [47]:
# linspoace can generate the data with specific num of interval and every data will be divided evenly
# also it consider upper bound and lower bounds
np.linspace(2,5, num=10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [48]:
np.linspace(0,9, num=10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
np.linspace(3,5, num=5)

array([3. , 3.5, 4. , 4.5, 5. ])

In [50]:
d1 = np.zeros(4)
print(d1)
print(d1.ndim)
print(d1.shape)
print(d1.size)

[0. 0. 0. 0.]
1
(4,)
4


In [51]:
d2 = np.zeros((3,4))
print(d2)
print(d2.ndim)
print(d2.shape)
print(d2.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
(3, 4)
12


In [52]:
d3 = np.zeros((1,2,3))   #it is giving 1 array of size(2,3)
print(d3)
print(d3.ndim)
print(d3.shape)
print(d3.size)


[[[0. 0. 0.]
  [0. 0. 0.]]]
3
(1, 2, 3)
6


In [53]:
d4 = np.zeros((2,2,2))   #giving 2 arraays of (2,2) 
print(d4)                #2 layers creating a depth of an array for making it 3d
print(d4.ndim)
print(d4.shape)
print(d4.size)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3
(2, 2, 2)
8


In [54]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.ones((3,4)) + 3

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [56]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [57]:
np.empty((3,6))   #it is giving an empty matrix with some random value 

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [58]:
np.eye(4)   #creating an identity matrix of order (4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.arange(16).reshape((2,4,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [63]:
np.arange(5).reshape((5,1))

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [67]:
np.arange(16).reshape((2,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [72]:
np.random.rand(2,3) #give us a dataset based on uniform distribution

array([[0.81453362, 0.47751264, 0.73437033],
       [0.30453663, 0.4245319 , 0.94364668]])

In [73]:
np.random.randn(4,5)  #give us a dataset based on standard normal distribution

array([[ 1.71007847,  1.06786956,  0.73241951, -0.2644759 , -0.37530621],
       [-0.1354612 , -0.02951951, -1.34454029,  1.0851795 ,  0.49332777],
       [ 1.66934031,  1.49726679,  1.13154249,  0.51932694, -0.92509168],
       [-1.61009695, -0.26388143,  0.99257112,  0.71534685, -0.00851947]])

In [79]:
# every time i executed this the value will change 
np.random.randint(1,5,(4,3))  #giving the array in bw 1 to 5 of size (4,3)

array([[2, 3, 2],
       [2, 1, 2],
       [3, 2, 3],
       [1, 2, 1]])

In [86]:
# to get the same value every time we will use seed function
np.random.seed(6)
np.random.randint(1,5,(4,3)) 

array([[3, 2, 4],
       [1, 3, 2],
       [4, 3, 1],
       [3, 2, 2]])

In [88]:
np.random.seed(68934)
np.random.randint(1,5,(4,3)) 

array([[2, 1, 3],
       [2, 1, 2],
       [2, 4, 2],
       [2, 2, 3]])

In [90]:
a5 = np.random.randint(2,6, (3,4))

In [91]:
a5

array([[3, 2, 3, 4],
       [5, 2, 4, 3],
       [3, 3, 3, 2]])

In [92]:
# getting sorted data
np.sort(a5)

array([[2, 3, 3, 4],
       [2, 3, 4, 5],
       [2, 3, 3, 3]])

In [93]:
# but the array is only sorted row wize
np.sort(a5, axis =1) 

array([[2, 3, 3, 4],
       [2, 3, 4, 5],
       [2, 3, 3, 3]])

In [95]:
a6 = np.random.randint(2,10,(3,3))

In [96]:
a6

array([[2, 8, 2],
       [8, 2, 4],
       [9, 9, 2]])

In [97]:
np.sort(a6, axis = 1)

array([[2, 2, 8],
       [2, 4, 8],
       [2, 9, 9]])

In [102]:
np.sort(a6, axis = 0, kind = 'mergesort')

array([[2, 2, 2],
       [8, 8, 2],
       [9, 9, 4]])

In [103]:
np.sort(a6)

array([[2, 2, 8],
       [2, 4, 8],
       [2, 9, 9]])

In [104]:
a6.max()

9

In [108]:
a6[2]

array([9, 9, 2])

In [111]:
a6[2:1:1] #[row,col,step]

array([], shape=(0, 3), dtype=int32)

In [113]:
a7 = np.random.randint(3,7,(7,7))

In [114]:
a7

array([[5, 4, 4, 6, 3, 3, 5],
       [5, 6, 3, 3, 6, 4, 5],
       [3, 4, 6, 5, 4, 6, 3],
       [6, 4, 3, 3, 6, 6, 4],
       [4, 6, 4, 6, 5, 4, 6],
       [4, 4, 5, 4, 4, 3, 6],
       [3, 5, 6, 4, 3, 5, 5]])

In [115]:
a7[3]

array([6, 4, 3, 3, 6, 6, 4])

In [116]:
a7[2:5] #excluding the upper bound

array([[3, 4, 6, 5, 4, 6, 3],
       [6, 4, 3, 3, 6, 6, 4],
       [4, 6, 4, 6, 5, 4, 6]])

In [117]:
a7[1:6:2]

array([[5, 6, 3, 3, 6, 4, 5],
       [6, 4, 3, 3, 6, 6, 4],
       [4, 4, 5, 4, 4, 3, 6]])

In [119]:
a7[2:5,2:6]

array([[6, 5, 4, 6],
       [3, 3, 6, 6],
       [4, 6, 5, 4]])

In [121]:
a7[2:5,3:5]

array([[5, 4],
       [3, 6],
       [6, 5]])

In [124]:
a8 = np.random.randint(3,6,(3,4))

In [123]:
a9 = np.random.randint(3,8,(3,4))

In [125]:
a8

array([[5, 4, 4, 3],
       [4, 4, 4, 4],
       [3, 5, 4, 4]])

In [126]:
a9

array([[6, 6, 5, 7],
       [4, 5, 4, 7],
       [3, 5, 5, 4]])

In [127]:
a8/0 #in nupy it will give infinity

C:\Users\himan\AppData\Local\Temp\ipykernel_13532\3747121839.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a8/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [128]:
a8*a9  #element wise multiplication

array([[30, 24, 20, 21],
       [16, 20, 16, 28],
       [ 9, 25, 20, 16]])

In [129]:
a8/a9

array([[0.83333333, 0.66666667, 0.8       , 0.42857143],
       [1.        , 0.8       , 1.        , 0.57142857],
       [1.        , 1.        , 0.8       , 1.        ]])

In [130]:
a10 = np.random.randint(3,6,(3,3))

In [132]:
a9*a10 #not the same size array 

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [139]:
# we can transpose matrix by .T
print(a8.T)
print(a8.T.shape)

[[5 4 3]
 [4 4 5]
 [4 4 4]
 [3 4 4]]
(4, 3)


In [143]:
print(a9)
print(a9.shape)

[[6 6 5 7]
 [4 5 4 7]
 [3 5 5 4]]
(3, 4)


In [142]:
# now we can do matrix multiplication because is compatible to do this
a8.T@a9   #matrix multiplication done by @ not by *

array([[55, 65, 56, 75],
       [55, 69, 61, 76],
       [52, 64, 56, 72],
       [46, 58, 51, 65]])

In [146]:
print(a8)

print(a8**2)

[[5 4 4 3]
 [4 4 4 4]
 [3 5 4 4]]
[[25 16 16  9]
 [16 16 16 16]
 [ 9 25 16 16]]
