In [1]:
import numpy as np
# numerical python liberary - data manipulation of array and matrics

In [2]:
a = np.array([1,2,3,4,5,6])

In [3]:
type(a) #n dimensional array

numpy.ndarray

In [4]:
import array as ar

In [55]:
ar.array('i',[1,2,3,4,5])

array('i', [1, 2, 3, 4, 5])

In [6]:
np.array([1,34.56,67,'raj'])

array(['1', '34.56', '67', 'raj'], dtype='<U32')

In [7]:
np.array([1,34.56,67,'raj'], ndmin = 3)

array([[['1', '34.56', '67', 'raj']]], dtype='<U32')

In [8]:
np.array([1,34.56,67,'raj'], ndmin = 1)

array(['1', '34.56', '67', 'raj'], dtype='<U32')

In [9]:
np.array([1,34.56,67,'raj'], ndmin = 0)

array(['1', '34.56', '67', 'raj'], dtype='<U32')

In [10]:
np.array([1,34.56,67,'raj'], ndmin = 2)

array([['1', '34.56', '67', 'raj']], dtype='<U32')

In [11]:
 np.array([[1,2,3],[4,5,6]]) #2dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
 np.array([[1,2,3],[4,5,6]], ndmin = 3)   #3d array

array([[[1, 2, 3],
        [4, 5, 6]]])

In [13]:
 np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
np.array([3,4,5,6], dtype = complex)

array([3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [15]:
np.array([3,4,5,6], dtype = str)

array(['3', '4', '5', '6'], dtype='<U1')

In [16]:
type(np.asarray([1,2,3,4,5]))

numpy.ndarray

In [17]:
np.asarray([3,4,5,6,7], dtype = np.float16)

array([3., 4., 5., 6., 7.], dtype=float16)

In [18]:
mat = np.mat([5,6])

In [19]:
mat

matrix([[5, 6]])

In [20]:
np.mat([5,6,7])

matrix([[5, 6, 7]])

In [21]:
type(mat)   #matrix is a sub class of array

numpy.matrix

In [22]:
# np.asanyarray - if dataset is available in any array so it won't do any conversion
np.asanyarray(mat)

matrix([[5, 6]])

In [23]:
# here the matrix is already avaiable in array so won't do any conversion


In [24]:
l = [4,5,6,7,8,9]
np.asanyarray(l)

array([4, 5, 6, 7, 8, 9])

In [25]:
# converted list into array


In [26]:
np.fromfunction(lambda i, j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
# what is happening here -  it is trying to create a numpy array from function
np.fromfunction(lambda i,j : i==j,(3,3))
# 3,3 is a order of matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
 np.fromfunction(lambda i,j : i**i, (2,2))

array([[1., 1.],
       [1., 1.]])

In [29]:
 np.fromfunction(lambda i,j : i**i, (3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [4, 4, 4]], dtype=int32)

In [30]:
np.fromstring('raj sahu', sep = " ")

C:\Users\himan\AppData\Local\Temp\ipykernel_10816\1007350494.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('raj sahu', sep = " ")


array([], dtype=float64)

In [31]:
np.fromstring('22-04-1997', sep = "-", )

array([  22.,    4., 1997.])

In [32]:
np.fromstring("4,6", sep = ",")

array([4., 6.])

In [33]:
a

array([1, 2, 3, 4, 5, 6])

In [34]:
a1 = np.array([5,6,7,8,9])

In [35]:
a2 = np.array([4,5,6,7,8])

In [36]:
a1

array([5, 6, 7, 8, 9])

In [37]:
a2

array([4, 5, 6, 7, 8])

In [38]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a3.ndim

2

In [41]:
a1.ndim

1

In [42]:
a1.size #element of an array

5

In [43]:
a2.size

5

In [44]:
a3.size

9

In [45]:
a1.shape

(5,)

In [46]:
a3.shape #(row,col)

(3, 3)

In [47]:
np.array([(2,3,4,5,6),(3,4,5,6,7)])

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [48]:
range(10)

range(0, 10)

In [49]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
range(3,5.6)

TypeError: 'float' object cannot be interpreted as an integer

In [51]:
np.arange(3,5.6)

array([3., 4., 5.])

In [52]:
np.arange(3,5.6,.2)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4])

In [53]:
 np.array([(1,2,3,4,5,6),(3,4,5,6,7)])

C:\Users\himan\AppData\Local\Temp\ipykernel_10816\2048534763.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([(1,2,3,4,5,6),(3,4,5,6,7)])


array([(1, 2, 3, 4, 5, 6), (3, 4, 5, 6, 7)], dtype=object)

In [54]:
 np.array([(1,2,3,4,5),(3,4,5,6,7)])

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])